// This file is generated automatically by Next.js
// Do not edit this file manually
// This file validates that all pages and layouts export the correct types

import type { AppRoutes, LayoutRoutes, ParamMap } from "./routes.js"
import type { ResolvingMetadata, ResolvingViewport } from "next/types.js"

type AppPageConfig<Route extends AppRoutes = AppRoutes> = {
  default: React.ComponentType<{ params: Promise<ParamMap[Route]> } & any> | ((props: { params: Promise<ParamMap[Route]> } & any) => React.ReactNode | Promise<React.ReactNode> | never | void | Promise<void>)
  generateStaticParams?: (props: { params: ParamMap[Route] }) => Promise<any[]> | any[]
  generateMetadata?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingMetadata
  ) => Promise<any> | any
  generateViewport?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingViewport
  ) => Promise<any> | any
  metadata?: any
  viewport?: any
}

type LayoutConfig<Route extends LayoutRoutes = LayoutRoutes> = {
  default: React.ComponentType<LayoutProps<Route>> | ((props: LayoutProps<Route>) => React.ReactNode | Promise<React.ReactNode> | never | void | Promise<void>)
  generateStaticParams?: (props: { params: ParamMap[Route] }) => Promise<any[]> | any[]
  generateMetadata?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingMetadata
  ) => Promise<any> | any
  generateViewport?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingViewport
  ) => Promise<any> | any
  metadata?: any
  viewport?: any
}


// Validate ../../src/app/benchmark/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/benchmark">> = Specific
  const handler = {} as typeof import("../../src/app/benchmark/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/dashboard/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboard">> = Specific
  const handler = {} as typeof import("../../src/app/dashboard/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/flash-thought/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/flash-thought">> = Specific
  const handler = {} as typeof import("../../src/app/flash-thought/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/inspiration/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/inspiration">> = Specific
  const handler = {} as typeof import("../../src/app/inspiration/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/knowledge-base/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/knowledge-base">> = Specific
  const handler = {} as typeof import("../../src/app/knowledge-base/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/notification/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/notification">> = Specific
  const handler = {} as typeof import("../../src/app/notification/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/">> = Specific
  const handler = {} as typeof import("../../src/app/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/produce-flow/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/produce-flow">> = Specific
  const handler = {} as typeof import("../../src/app/produce-flow/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/publish/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/publish">> = Specific
  const handler = {} as typeof import("../../src/app/publish/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/qa-collect/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/qa-collect">> = Specific
  const handler = {} as typeof import("../../src/app/qa-collect/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/review/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/review">> = Specific
  const handler = {} as typeof import("../../src/app/review/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/script-template/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/script-template">> = Specific
  const handler = {} as typeof import("../../src/app/script-template/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/todo/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/todo">> = Specific
  const handler = {} as typeof import("../../src/app/todo/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/topic-library/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/topic-library">> = Specific
  const handler = {} as typeof import("../../src/app/topic-library/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}







// Validate ../../src/app/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/">> = Specific
  const handler = {} as typeof import("../../src/app/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}
