var R=require("../../chunks/ssr/[turbopack]_runtime.js")("server/app/knowledge-base/page.js")
R.c("server/chunks/ssr/[root-of-the-server]__0_2s_ys._.js")
R.c("server/chunks/ssr/node_modules_next_dist_1n3w9lb._.js")
R.c("server/chunks/ssr/[root-of-the-server]__0iknhq1._.js")
R.c("server/chunks/ssr/[root-of-the-server]__0j26pto._.js")
R.c("server/chunks/ssr/src_1u60sjk._.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_0wpq8j3._.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_builtin_forbidden_0symwr9.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_builtin_unauthorized_0l_sp0x.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_builtin_global-error_0q-w892.js")
R.c("server/chunks/ssr/_next-internal_server_app_knowledge-base_page_actions_09b5sj9.js")
R.m(70733)
module.exports=R.m(70733).exports
